name: Reentrenamiento Automático

on:
  push:
    branches:
      - main

jobs:
  retrain-model:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar reentrenamiento
      run: |
        python retraining.py

    - name: Confirmar modelo actualizado (opcional)
      run: |
        ls -lh model/
